'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */

    await queryInterface.bulkInsert('perfumes', [
      {
        name: "Eros",
        brand_id: 1,
        use_yn: "Y",
        sex: "M",
        description: "Eros by Versace is a Aromatic Fougere fragrance for men. Eros was launched in 2012. The nose behind this fragrance is Aurelien Guichard. Top notes are Mint, Green Apple and Lemon; middle notes are Tonka Bean, Ambroxan and Geranium; base notes are Madagascar Vanilla, Virginian Cedar, Atlas Cedar, Vetiver and Oakmoss.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/69867m.jpg",
        top_note: "1",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Gianni Versace Versace",
        brand_id: 1,
        use_yn: "Y",
        sex: "F",
        description: "Gianni Versace by Versace is a Chypre Floral fragrance for women. Gianni Versace was launched in 1981. Top notes are Spices, Aldehydes, Fruity Notes and Bergamot; middle notes are Carnation, Tuberose, Gardenia, Orris Root, Narcissus, Jasmine and Lily-of-the-Valley; base notes are Oakmoss, Benzoin, Incense, Myrrh, Amber, Leather, Sandalwood and Patchouli.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/65451w.jpg",
        top_note: "2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Bright Crystal",
        brand_id: 1,
        use_yn: "Y",
        sex: "F",
        description: "Bright Crystal by Versace is a Floral Fruity fragrance for women. Bright Crystal was launched in 2006. The nose behind this fragrance is Alberto Morillas. Top notes are Yuzu, Pomegranate and Ice; middle notes are Peony, Lotus and Magnolia; base notes are Musk, Mahogany and Amber..",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/61100w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Black Bvlgari",
        brand_id: 2,
        use_yn: "Y",
        sex: "N",
        description: "Black by Bvlgari is a Amber Woody fragrance for women and men. Black was launched in 1998. The nose behind this fragrance is Annick Menardo. Top notes are Green Tea, Bergamot and Rose; middle notes are Sandalwood, Cedar and Jasmine; base notes are Leather, Vanilla, Amber, Musk and Oakmoss.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/74527m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "BLV Bvlgari",
        brand_id: 2,
        use_yn: "Y",
        sex: "F",
        description: "BLV by Bvlgari is a Floral Woody Musk fragrance for women. BLV was launched in 2000. The nose behind this fragrance is Alberto Morillas. Top notes are Ginger and Bergamot; middle notes are Wisteria and Flax; base notes are Musk, Sandalwood, Black locust and Vanilla.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/805m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Bvlgari Pour Femme Bvlgari",
        brand_id: 2,
        use_yn: "Y",
        sex: "F",
        description: "Bvlgari Pour Femme by Bvlgari is a Floral fragrance for women. Bvlgari Pour Femme was launched in 1994. The nose behind this fragrance is Sophia Grojsman. Top notes are Violet, Carnation, Raspberry, Peach, Coriander, Orange Blossom, Sichuan Pepper and Bergamot; middle notes are iris, Bulgarian Rose, Heliotrope, Orris Root, Egyptian Jasmine and Lily-of-the-Valley; base notes are Musk, Green Tea, Woody Notes, Sandalwood, Vanilla, Amber, Benzoin, Styrax and Cedar.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/62266m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Le Labo Santal 33 Perfume",
        brand_id: 19,
        use_yn: "Y",
        sex: "F",
        description: "Le Labo Santal 33 Perfume by Le Labo, Show everyone you're a class act when you're dressed to the nines and wearing Santal 33, a clean and decadent women's fragrance.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/77922w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Aventus Cologne",
        brand_id: 14,
        use_yn: "Y",
        sex: "M",
        description: "Those who buy Creed Aventus will discover a cologne that captures the classic tradition of this brand with distinctly modern touches. The result of this innovative blend is a sophisticated fragrance that's perfect for any occasion. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/68420m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Green Irish Tweed Cologne",
        brand_id: 14,
        use_yn: "Y",
        sex: "M",
        description: "Green Irish Tweed Cologne by Creed, This sporty mix is sure to make any man feel like a famous movie star. With hints of violet leaves, Mysore sandalwood, Florentine iris, ambergris, and French verbena, Green Irish Tweed is known for its longevity and reasonable sillage.  ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/68420m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Original Vetiver Cologne",
        brand_id: 14,
        use_yn: "Y",
        sex: "M",
        description: "Original Vetiver Cologne by Creed, Modern and sophisticated, Original Vetiver is a refreshing cologne for the active man. The masculine fragrance, launched in 2004, is inspired by the clean, clear scents of the great outdoors. Crisp bergamot and mandarin orange are the top notes. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/68420m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Virgin Island Water Cologne",
        brand_id: 14,
        use_yn: "Y",
        sex: "M",
        description: "Virgin Island Water Cologne by Creed, Virgin Island Water is an exotic paradise in aromatic form. The bright, refreshing cologne, released in 2007, brings you all of the delicious aromas of the tropics. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/68420m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Diptyque Vetyverio Perfume",
        brand_id: 15,
        use_yn: "Y",
        sex: "N",
        description: "Diptyque Vetyverio Perfume by Diptyque, Diptyque Vetyverio is a unisex fragrance released in May 2010 by famed French perfume house Diptyque. This perfume is an elegant blend of citrus, floral, and earthy notes that can be used for any season or occasion. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/68420m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Vera Wang Cologne",
        brand_id: 9,
        use_yn: "Y",
        sex: "M",
        description: "Vera Wang Cologne by Vera Wang, Released in 2004, Vera Wang Cologne for Men is a classy, seductive fragrance that women will find incredibly enticing.  ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/1426m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Princess Perfume",
        brand_id: 9,
        use_yn: "Y",
        sex: "F",
        description: "Princess Perfume by Vera Wang, Were you born to rule? No matter your age, there is magic inside you that makes you royalty. Princess is a fragrance to celebrate everything that makes you special. Rule your world with this modern and playful confidence booster.  ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/61076w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Portrait Of A Lady Perfume",
        brand_id: 16,
        use_yn: "Y",
        sex: "F",
        description: "Portrait Of A Lady Perfume by Frederic Malle, Whether you secretly channel Henry James’ heroine, Isabel Archer, or you simply enjoy your own simple pleasures, Portrait of a Lady exudes sophistication without consequence. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/76057w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Jo Malone Lime Basil & Mandarin Cologne",
        brand_id: 17,
        use_yn: "Y",
        sex: "N",
        description: "Jo Malone Lime Basil & Mandarin Cologne by Jo Malone, Jo Malone Lime Basil & Mandarin is the signature scent of Jo Malone. Introduced in 1991, this crisp and zesty fragrance is ideal for anyone, man or woman, looking for a classic fragrance.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/76057w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Eternity Cologne",
        brand_id: 5,
        use_yn: "Y",
        sex: "M",
        description: "Wear your confidence and charisma as you spritz the Calvin Klein Eternity Cologne EDT Spray on yourself! It brightly opens up with the zesty notes of Mandarin orange, lemon, and bergamot and the soothing lavender. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/352m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Eternity",
        brand_id: 5,
        use_yn: "Y",
        sex: "F",
        description: "A truly timeless Eau De Parfum became one of the most beloved perfumes that became part of the Fragrance Hall of Fame. This exquisite scent has somehow captured the very essence of summer, making it a perfect choice for the season as it evokes heady blooms in hazy, pleasant sunlight.  ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/352w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Obsession Cologne",
        brand_id: 5,
        use_yn: "Y",
        sex: "M",
        description: "Obsession Cologne by Calvin Klein, A classically elegant, sensual men’s fragrance, Obsession is an enduring woody oriental enhanced by elements of spice, amber and aromatic herbs.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/1002m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Euphoria",
        brand_id: 5,
        use_yn: "Y",
        sex: "F",
        description: "Euphoria by Calvin Klein is a confidently sensual floral oriental fragrance with a dark allure, combining intoxicating blooms and exotic fruits with amber and warm spice. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/60582w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Jubilation Xxv Cologne",
        brand_id: 3,
        use_yn: "Y",
        sex: "M",
        description: "Amouage Jubilation Xxv Cologne by Amouage, Start every new day with unparalleled confidence with Amouage Jubilation Xxv, a powerhouse men’s fragrance by Amouage. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/71094m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Interlude Cologne",
        brand_id: 3,
        use_yn: "Y",
        sex: "M",
        description: "Amouage Interlude Cologne by Amouage, Amouage Interlude is a masculine cologne that features accords of balsamic and amber. This fragrance was launched alongside a feminine perfume by the same name in 2012 by the fragrance house Amouage.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/71093m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Epic",
        brand_id: 3,
        use_yn: "Y",
        sex: "F",
        description: "Amouage Epic Perfume by Amouage, Amouage Epic is a floral fragrance for women that reminds of oriental elegance of yesteryear.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/71446w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Imitation",
        brand_id: 3,
        use_yn: "Y",
        sex: "F",
        description: "Amouage Imitation Perfume by Amouage, If you are search of an original perfume with a new balance of your favorite aromas, Amouage Imitation for women was made for you. This fragrance was released in 2018 with mature and confident ladies in mind.",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/76972w.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        name: "Nautica Voyage Cologne",
        brand_id: 7,
        use_yn: "Y",
        sex: "M",
        description: "Nautica Voyage Cologne by Nautica, Debuting in 2006, Nautica Voyage evokes the freshness and vibrancy of the sea. This easy-wear-scent begins with top notes of cool green leaf and fresh-cut apple. The heart of the cologne offers notes of drenched mimosa, water lotus and aquatic elements. ",
        pic1: "https://img.fragrancex.com/images/products/parent/medium/60906m.jpg",
        top_note: "1,2",
        middle_note: "1,2",
        base_note: "2",
        created_at: new Date,
        updated_at: new Date,
      },

    ]);

  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
