'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */

    await queryInterface.bulkInsert('reviews', [
      {
        longevity: "30",
        sillage: "20",
        male: "50",
        female: "50",
        value: "70",
        overall: "3",
        title: "I found this",
        content: "It really reminds me Arab Emirates. unisex, and lasts not so long",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "1",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "50",
        sillage: "40",
        male: "80",
        female: "20",
        value: "10",
        overall: "3",
        title: "I don't recommend this",
        content: "really disappointed",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "2",
        title: "It's really strong",
        content: "It's really strong! and lasts long, I recommend",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "5",
        title: "It was present for my boyfriend",
        content: "He likes this! ",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "5",
        title: "It's really strong",
        content: "It's really strong! and lasts long, I recommend",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "30",
        sillage: "20",
        male: "50",
        female: "50",
        value: "70",
        overall: "4",
        title: "I would buy again",
        content: "It really reminds me Arab Emirates. unisex, and lasts not so long",
        use_yn: "Y",
        perfume_id: "3",
        user_id: "2",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "5",
        title: "I would buy again",
        content: "Never disappointing compliments always",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "4",
        title: "Excellent Smokey Fragrance",
        content: "I love everything about this fragrance. The sweet smokey/woodsy scent really reminds me of how my clothes would smell after sitting around a campfire for hours when I was younger. It lasts all day, and it's sillage is moderate. It's very much worth the price and I'd highly recommend for anyone who is looking for a fragrance with this type of scent.",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "3",
        title: "The best",
        content: "I love this parfume , it's amazing",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "5",
        title: "amazing",
        content: "Great",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "1",
        title: "very good",
        content: "i like it",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },
      {
        longevity: "70",
        sillage: "70",
        male: "100",
        female: "0",
        value: "80",
        overall: "3",
        title: "hold for may be 12Hrs",
        content: "great and long lasting",
        use_yn: "Y",
        perfume_id: "1",
        user_id: "3",
        created_at: new Date,
        updated_at: new Date,
      },

    ]);

  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
